version: 2
updates:
  # Rust dependencies (Cargo)
  - package-ecosystem: "cargo"
    directory: "/data"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/data-lib"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/data-wasm"
    schedule:
      interval: "weekly"
  # JavaScript dependencies (npm)
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"
